/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The system actor represents an action performed by the system, such as a scheduled task, migration, or other automated process. Some actions may not have a specific actor and will default to the system actor.
*/
export class ActorSystem {
    'type': ActorSystem.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActorSystem.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ActorSystem.attributeTypeMap;
    }
}

export namespace ActorSystem {
    export enum TypeEnum {
        System = <any> 'system'
    }
}
