/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActorApi } from './actorApi';
import { ActorCsv } from './actorCsv';
import { ActorIntegration } from './actorIntegration';
import { ActorRunnSupport } from './actorRunnSupport';
import { ActorSystem } from './actorSystem';
import { ActorUser } from './actorUser';

/**
* An actor represents an entity that can perform actions such as a user, api key, or system process. Each actor type has a unique set of properties. The `type` property is used to determine the actor type.
*/
export class Actor {
    'type': Actor.TypeEnum;
    /**
    * The id of the user who uploaded the csv file.
    */
    'userId': number;
    /**
    * The email of the user who uploaded the csv file.
    */
    'userEmail'?: string;
    /**
    * The id of the api key.
    */
    'tokenId': number;
    /**
    * The name of the api key.
    */
    'tokenName': string;
    /**
    * The api version.
    */
    'apiVersion': string;
    /**
    * The id of the integration.
    */
    'id': number;
    /**
    * The name of the integration.
    */
    'name': string;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "Actor.TypeEnum"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "userEmail",
            "baseName": "userEmail",
            "type": "string"
        },
        {
            "name": "tokenId",
            "baseName": "tokenId",
            "type": "number"
        },
        {
            "name": "tokenName",
            "baseName": "tokenName",
            "type": "string"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Actor.attributeTypeMap;
    }
}

export namespace Actor {
    export enum TypeEnum {
        User = <any> 'user',
        RunnSupport = <any> 'runn_support',
        Api = <any> 'api',
        Csv = <any> 'csv',
        Integration = <any> 'integration',
        System = <any> 'system'
    }
}
