/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The api actor represents an action performed by an api key.
*/
export class ActorApi {
    'type': ActorApi.TypeEnum;
    /**
    * The id of the api key.
    */
    'tokenId': number;
    /**
    * The name of the api key.
    */
    'tokenName': string;
    /**
    * The api version.
    */
    'apiVersion': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActorApi.TypeEnum"
        },
        {
            "name": "tokenId",
            "baseName": "tokenId",
            "type": "number"
        },
        {
            "name": "tokenName",
            "baseName": "tokenName",
            "type": "string"
        },
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActorApi.attributeTypeMap;
    }
}

export namespace ActorApi {
    export enum TypeEnum {
        Api = <any> 'api'
    }
}
