/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The csv actor represents an action performed by a csv file upload.
*/
export class ActorCsv {
    'type': ActorCsv.TypeEnum;
    /**
    * The id of the user who uploaded the csv file.
    */
    'userId'?: number;
    /**
    * The email of the user who uploaded the csv file.
    */
    'userEmail'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActorCsv.TypeEnum"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "userEmail",
            "baseName": "userEmail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActorCsv.attributeTypeMap;
    }
}

export namespace ActorCsv {
    export enum TypeEnum {
        Csv = <any> 'csv'
    }
}
