/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Actual {
    /**
    * The unique identifier for the actual
    */
    'id': number;
    /**
    * The date the actual took place. Format: YYYY-MM-DD
    */
    'date': string;
    /**
    * The number of billable minutes for the actual
    */
    'billableMinutes': number;
    /**
    * The number of nonbillable minutes for the actual
    */
    'nonbillableMinutes': number;
    /**
    * A note or comment related to the billable minutes, if any.
    */
    'billableNote': string;
    /**
    * A note or comment related to the nonbillable minutes, if any.
    */
    'nonbillableNote': string;
    /**
    * The ID referencing the phase of the actual, if applicable.
    */
    'phaseId': number;
    /**
    * The ID referencing the person associated with the actual.
    */
    'personId': number;
    /**
    * The ID referencing the project associated with the actual.
    */
    'projectId': number;
    /**
    * The ID referencing the role associated with the actual.
    */
    'roleId': number;
    /**
    * The ID referencing the workstream of the actual, if applicable.
    */
    'workstreamId': number;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "billableMinutes",
            "baseName": "billableMinutes",
            "type": "number"
        },
        {
            "name": "nonbillableMinutes",
            "baseName": "nonbillableMinutes",
            "type": "number"
        },
        {
            "name": "billableNote",
            "baseName": "billableNote",
            "type": "string"
        },
        {
            "name": "nonbillableNote",
            "baseName": "nonbillableNote",
            "type": "string"
        },
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Actual.attributeTypeMap;
    }
}

