/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActualInput {
    /**
    * The date this actual is for. Format: YYYY-MM-DD
    */
    'date': string;
    /**
    * The number of minutes that are billable. Either this or nonbillableMinutes must be set
    */
    'billableMinutes': number = 0;
    /**
    * The number of minutes that are non billable. Either this or billableMinutes must be set
    */
    'nonbillableMinutes': number = 0;
    /**
    * A note about the billable minutes
    */
    'billableNote'?: string;
    /**
    * A note about the nonbillable minutes
    */
    'nonbillableNote'?: string;
    /**
    * The phase this actual is for, if any
    */
    'phaseId'?: number;
    /**
    * The person this actual is for
    */
    'personId': number;
    /**
    * The project this actual is for
    */
    'projectId': number;
    /**
    * The role the person was in when for this actual
    */
    'roleId': number;
    /**
    * The workstream the actual belongs to
    */
    'workstreamId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "billableMinutes",
            "baseName": "billableMinutes",
            "type": "number"
        },
        {
            "name": "nonbillableMinutes",
            "baseName": "nonbillableMinutes",
            "type": "number"
        },
        {
            "name": "billableNote",
            "baseName": "billableNote",
            "type": "string"
        },
        {
            "name": "nonbillableNote",
            "baseName": "nonbillableNote",
            "type": "string"
        },
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ActualInput.attributeTypeMap;
    }
}

