/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Assignment {
    /**
    * The unique identifier for the assignment.
    */
    'id': number;
    /**
    * id referencing the person associated with the assignment.
    */
    'personId': number;
    /**
    * The start date of the assignment. Format: YYYY-MM-DD
    */
    'startDate': string;
    /**
    * The end date of the assignment. Format: YYYY-MM-DD
    */
    'endDate': string;
    /**
    * The ID referencing the project to which the assignment belongs.
    */
    'projectId': number;
    /**
    * The number of minutes allocated to the assignment per day.
    */
    'minutesPerDay': number;
    /**
    * The ID referencing the role associated with the assignment.
    */
    'roleId': number;
    /**
    * A flag indicating whether the assignment is currently active.
    */
    'isActive': boolean;
    'note': string;
    /**
    * A flag indicating whether the assignment is billable.
    */
    'isBillable': boolean;
    'phaseId': number;
    /**
    * A flag indicating if the assignment falls on a non-working day.
    */
    'isNonWorkingDay': boolean;
    /**
    * A flag indicating if the assignment is a template.
    */
    'isTemplate': boolean;
    /**
    * A flag indicating if the assignment\'s person is a placeholder.
    */
    'isPlaceholder': boolean;
    'workstreamId': number;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "isBillable",
            "baseName": "isBillable",
            "type": "boolean"
        },
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "isNonWorkingDay",
            "baseName": "isNonWorkingDay",
            "type": "boolean"
        },
        {
            "name": "isTemplate",
            "baseName": "isTemplate",
            "type": "boolean"
        },
        {
            "name": "isPlaceholder",
            "baseName": "isPlaceholder",
            "type": "boolean"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Assignment.attributeTypeMap;
    }
}

