/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BadRequest {
    'error': BadRequest.ErrorEnum;
    'message': string;
    'statusCode': BadRequest.StatusCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "BadRequest.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "BadRequest.StatusCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return BadRequest.attributeTypeMap;
    }
}

export namespace BadRequest {
    export enum ErrorEnum {
        BadRequest = <any> 'Bad Request'
    }
    export enum StatusCodeEnum {
        NUMBER_400 = <any> 400
    }
}
