/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RosteredDays } from './rosteredDays';

export class Contract {
    'id': number;
    'costPerHour': number;
    'employmentType': string;
    'minutesPerDay': number;
    'rosteredDays': RosteredDays;
    /**
    * Format: YYYY-MM-DD
    */
    'startDate': string;
    /**
    * Format: YYYY-MM-DD
    */
    'endDate': string;
    'roleId': number;
    'personId': number;
    /**
    * This feature is currently hidden, and can not be seen in the app
    */
    'jobTitle': string;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "costPerHour",
            "baseName": "costPerHour",
            "type": "number"
        },
        {
            "name": "employmentType",
            "baseName": "employmentType",
            "type": "string"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "rosteredDays",
            "baseName": "rosteredDays",
            "type": "RosteredDays"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Contract.attributeTypeMap;
    }
}

