/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateAssignmentRequest {
    /**
    * The phase this assignment is for, if any
    */
    'phaseId'?: number;
    /**
    * The person this assignment is for
    */
    'personId': number;
    /**
    * The project this assignment is for
    */
    'projectId': number;
    /**
    * The role the person will be in for this assignment
    */
    'roleId': number;
    /**
    * The date this assignment starts. Format: YYYY-MM-DD
    */
    'startDate': string;
    /**
    * The date this assignment ends. When using isNonWorkingDay=true, this needs to be the same as the startDate. Format: YYYY-MM-DD
    */
    'endDate': string;
    /**
    * How many minutes per day are assigned
    */
    'minutesPerDay': number = 0;
    /**
    * A note about this assignment
    */
    'note'?: string;
    /**
    * Whether this assignment is billable. This can only be set if this assignment is for a project without a non-billable pricing model or if it is for an external client
    */
    'isBillable'?: boolean = true;
    /**
    * Determine whether this assignment is for a single weekend day or a single holiday. If left blank it will be set automatically
    */
    'isNonWorkingDay'?: boolean;
    /**
    * The workstream this assignment is for, if any
    */
    'workstreamId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "isBillable",
            "baseName": "isBillable",
            "type": "boolean"
        },
        {
            "name": "isNonWorkingDay",
            "baseName": "isNonWorkingDay",
            "type": "boolean"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateAssignmentRequest.attributeTypeMap;
    }
}

