/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateInvitationRequest {
    /**
    * Email for the invitation.
    */
    'email': string;
    /**
    * Permission level
    */
    'userType': CreateInvitationRequest.UserTypeEnum;
    /**
    * Financial permission level
    */
    'financialPermission': CreateInvitationRequest.FinancialPermissionEnum;
    /**
    * Email address of user the invite should be sent from (must be a Runn user with admin permissions).
    */
    'fromUser': string;
    /**
    * Permissions for editing projects. (deprecated: use manageProjectsPermission)
    */
    'editProjectsPermission': CreateInvitationRequest.EditProjectsPermissionEnum;
    /**
    * Permissions for editing other parts of the account (people, clients, teams etc.)
    */
    'editOthersPermission': CreateInvitationRequest.EditOthersPermissionEnum;
    /**
    * Permissions for managing projects.
    */
    'manageProjectsPermission': CreateInvitationRequest.ManageProjectsPermissionEnum;
    /**
    * Permissions for managing other parts of the account (people, clients, teams etc.)
    */
    'manageOthersPermission': CreateInvitationRequest.ManageOthersPermissionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "userType",
            "type": "CreateInvitationRequest.UserTypeEnum"
        },
        {
            "name": "financialPermission",
            "baseName": "financialPermission",
            "type": "CreateInvitationRequest.FinancialPermissionEnum"
        },
        {
            "name": "fromUser",
            "baseName": "fromUser",
            "type": "string"
        },
        {
            "name": "editProjectsPermission",
            "baseName": "editProjectsPermission",
            "type": "CreateInvitationRequest.EditProjectsPermissionEnum"
        },
        {
            "name": "editOthersPermission",
            "baseName": "editOthersPermission",
            "type": "CreateInvitationRequest.EditOthersPermissionEnum"
        },
        {
            "name": "manageProjectsPermission",
            "baseName": "manageProjectsPermission",
            "type": "CreateInvitationRequest.ManageProjectsPermissionEnum"
        },
        {
            "name": "manageOthersPermission",
            "baseName": "manageOthersPermission",
            "type": "CreateInvitationRequest.ManageOthersPermissionEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvitationRequest.attributeTypeMap;
    }
}

export namespace CreateInvitationRequest {
    export enum UserTypeEnum {
        Admin = <any> 'admin',
        Editor = <any> 'editor',
        ViewerAll = <any> 'viewer_all',
        ViewerBasic = <any> 'viewer_basic',
        TimesheetOnly = <any> 'timesheet_only',
        Manager = <any> 'manager',
        Contributor = <any> 'contributor'
    }
    export enum FinancialPermissionEnum {
        All = <any> 'all',
        NoSalaries = <any> 'no_salaries',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditOthersPermissionEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
    export enum ManageProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum ManageOthersPermissionEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
}
