/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreatePersonRequestRosteredDays } from './createPersonRequestRosteredDays';
import { Reference } from './reference';
import { UpdatePersonRequestTagsInner } from './updatePersonRequestTagsInner';

export class CreatePersonRequest {
    'firstName': string;
    'lastName': string;
    'email'?: string;
    'holidaysGroupId'?: number;
    'tags'?: Array<UpdatePersonRequestTagsInner>;
    'references'?: Array<Reference>;
    'roleId': number;
    /**
    * Defaults to today. Format: YYYY-MM-DD
    */
    'startDate'?: string;
    /**
    * Format: YYYY-MM-DD
    */
    'endDate'?: string;
    /**
    * The type of employment for the contract.
    */
    'employmentType'?: CreatePersonRequest.EmploymentTypeEnum = CreatePersonRequest.EmploymentTypeEnum.Employee;
    /**
    * Defaults to the role\'s cost per hour
    */
    'costPerHour'?: number;
    /**
    * Defaults to the account\'s default minutes per day
    */
    'minutesPerDay'?: number;
    'rosteredDays'?: CreatePersonRequestRosteredDays;
    /**
    * This feature is currently hidden, and can not be seen in the app
    */
    'jobTitle'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "holidaysGroupId",
            "baseName": "holidaysGroupId",
            "type": "number"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<UpdatePersonRequestTagsInner>"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "employmentType",
            "baseName": "employmentType",
            "type": "CreatePersonRequest.EmploymentTypeEnum"
        },
        {
            "name": "costPerHour",
            "baseName": "costPerHour",
            "type": "number"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "rosteredDays",
            "baseName": "rosteredDays",
            "type": "CreatePersonRequestRosteredDays"
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreatePersonRequest.attributeTypeMap;
    }
}

export namespace CreatePersonRequest {
    export enum EmploymentTypeEnum {
        Employee = <any> 'employee',
        Contractor = <any> 'contractor'
    }
}
