/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateInvitationRequestAllOfAnyOf {
    /**
    * Permissions for editing projects. (deprecated: use manageProjectsPermission)
    */
    'editProjectsPermission': CreateInvitationRequestAllOfAnyOf.EditProjectsPermissionEnum;
    /**
    * Permissions for editing other parts of the account (people, clients, teams etc.)
    */
    'editOthersPermission': CreateInvitationRequestAllOfAnyOf.EditOthersPermissionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "editProjectsPermission",
            "baseName": "editProjectsPermission",
            "type": "CreateInvitationRequestAllOfAnyOf.EditProjectsPermissionEnum"
        },
        {
            "name": "editOthersPermission",
            "baseName": "editOthersPermission",
            "type": "CreateInvitationRequestAllOfAnyOf.EditOthersPermissionEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvitationRequestAllOfAnyOf.attributeTypeMap;
    }
}

export namespace CreateInvitationRequestAllOfAnyOf {
    export enum EditProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditOthersPermissionEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
}
