/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateProjectRequestAnyOf } from './createProjectRequestAnyOf';
import { CreateProjectRequestAnyOf1 } from './createProjectRequestAnyOf1';
import { CreateProjectRequestAnyOf1FromTemplate } from './createProjectRequestAnyOf1FromTemplate';
import { Reference } from './reference';

export class CreateProjectRequest {
    'emoji'?: string;
    'name': string;
    'isConfirmed'?: boolean;
    'isTemplate'?: boolean;
    /**
    * Budget value in local currency
    */
    'budget'?: number;
    /**
    * Expenses budget value in local currency
    */
    'expensesBudget'?: number;
    'clientId': number;
    'teamId'?: number;
    /**
    * Defaults to \'tm\' if not specified
    */
    'pricingModel'?: CreateProjectRequest.PricingModelEnum;
    /**
    * Used to create initial project rates. Uses standard rate card if not specified
    */
    'rateCardId'?: number;
    /**
    * Defaults to account rate type if not specified
    */
    'rateType'?: CreateProjectRequest.RateTypeEnum;
    'references'?: Array<Reference>;
    /**
    * List of User IDs that manage the project.
    */
    'managerIds'?: Set<number>;
    'fromTemplate': CreateProjectRequestAnyOf1FromTemplate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emoji",
            "baseName": "emoji",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isConfirmed",
            "baseName": "isConfirmed",
            "type": "boolean"
        },
        {
            "name": "isTemplate",
            "baseName": "isTemplate",
            "type": "boolean"
        },
        {
            "name": "budget",
            "baseName": "budget",
            "type": "number"
        },
        {
            "name": "expensesBudget",
            "baseName": "expensesBudget",
            "type": "number"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "number"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number"
        },
        {
            "name": "pricingModel",
            "baseName": "pricingModel",
            "type": "CreateProjectRequest.PricingModelEnum"
        },
        {
            "name": "rateCardId",
            "baseName": "rateCardId",
            "type": "number"
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "CreateProjectRequest.RateTypeEnum"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "managerIds",
            "baseName": "managerIds",
            "type": "Set<number>"
        },
        {
            "name": "fromTemplate",
            "baseName": "fromTemplate",
            "type": "CreateProjectRequestAnyOf1FromTemplate"
        }    ];

    static getAttributeTypeMap() {
        return CreateProjectRequest.attributeTypeMap;
    }
}

export namespace CreateProjectRequest {
    export enum PricingModelEnum {
        Fp = <any> 'fp',
        Tm = <any> 'tm',
        Nb = <any> 'nb'
    }
    export enum RateTypeEnum {
        Hours = <any> 'hours',
        Days = <any> 'days'
    }
}
