/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateCheckboxCustomFieldRequest {
    'name': string;
    'description'?: string;
    /**
    * The field type of the custom field
    */
    'model': CreateCheckboxCustomFieldRequest.ModelEnum;
    'required': boolean = false;
    'showInPlanner': boolean = false;
    'filterableInPlanner': boolean = true;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "CreateCheckboxCustomFieldRequest.ModelEnum"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "showInPlanner",
            "baseName": "showInPlanner",
            "type": "boolean"
        },
        {
            "name": "filterableInPlanner",
            "baseName": "filterableInPlanner",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CreateCheckboxCustomFieldRequest.attributeTypeMap;
    }
}

export namespace CreateCheckboxCustomFieldRequest {
    export enum ModelEnum {
        Person = <any> 'PERSON',
        Project = <any> 'PROJECT'
    }
}
