/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateInvitationRequestAllOfAnyOf1 {
    /**
    * Permissions for managing projects.
    */
    'manageProjectsPermission': CreateInvitationRequestAllOfAnyOf1.ManageProjectsPermissionEnum;
    /**
    * Permissions for managing other parts of the account (people, clients, teams etc.)
    */
    'manageOthersPermission': CreateInvitationRequestAllOfAnyOf1.ManageOthersPermissionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "manageProjectsPermission",
            "baseName": "manageProjectsPermission",
            "type": "CreateInvitationRequestAllOfAnyOf1.ManageProjectsPermissionEnum"
        },
        {
            "name": "manageOthersPermission",
            "baseName": "manageOthersPermission",
            "type": "CreateInvitationRequestAllOfAnyOf1.ManageOthersPermissionEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreateInvitationRequestAllOfAnyOf1.attributeTypeMap;
    }
}

export namespace CreateInvitationRequestAllOfAnyOf1 {
    export enum ManageProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum ManageOthersPermissionEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
}
