/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateRateCardRequestReferencesInner } from './createRateCardRequestReferencesInner';

export class CreateRateCardRequest {
    'name': string;
    'description': string;
    'references': Array<CreateRateCardRequestReferencesInner>;
    'isBlendedRateCard': boolean;
    'blendedRate': number;
    'rateType': CreateRateCardRequest.RateTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<CreateRateCardRequestReferencesInner>"
        },
        {
            "name": "isBlendedRateCard",
            "baseName": "isBlendedRateCard",
            "type": "boolean"
        },
        {
            "name": "blendedRate",
            "baseName": "blendedRate",
            "type": "number"
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "CreateRateCardRequest.RateTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return CreateRateCardRequest.attributeTypeMap;
    }
}

export namespace CreateRateCardRequest {
    export enum RateTypeEnum {
        Hours = <any> 'hours',
        Days = <any> 'days'
    }
}
