/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateProjectRequestAnyOf1FromTemplate } from './createProjectRequestAnyOf1FromTemplate';

export class CreateProjectRequestAnyOf1 {
    'fromTemplate': CreateProjectRequestAnyOf1FromTemplate;
    'name'?: string;
    'clientId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fromTemplate",
            "baseName": "fromTemplate",
            "type": "CreateProjectRequestAnyOf1FromTemplate"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateProjectRequestAnyOf1.attributeTypeMap;
    }
}

