/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CustomCheckboxFieldCollection {
    'name': string;
    'type': CustomCheckboxFieldCollection.TypeEnum;
    'customCheckboxId': number;
    'value': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CustomCheckboxFieldCollection.TypeEnum"
        },
        {
            "name": "customCheckboxId",
            "baseName": "customCheckboxId",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CustomCheckboxFieldCollection.attributeTypeMap;
    }
}

export namespace CustomCheckboxFieldCollection {
    export enum TypeEnum {
        Checkbox = <any> 'checkbox'
    }
}
