/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CustomFieldText {
    /**
    * Unique identifier for the custom field text
    */
    'id': number;
    /**
    * Display name for the custom field text
    */
    'name': string;
    'description': string;
    /**
    * The field type of the custom field
    */
    'model': CustomFieldText.ModelEnum;
    /**
    * Whether or not the text is a required field
    */
    'required': boolean;
    /**
    * Whether or not the custom field text is shown in the project or person planner in the app UI
    */
    'showInPlanner': boolean;
    /**
    * The sort order of the custom field text
    */
    'sortOrder': number;
    /**
    * Whether or not the custom field text is filterable in the project or person planner in the app UI
    */
    'filterableInPlanner': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "CustomFieldText.ModelEnum"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "showInPlanner",
            "baseName": "showInPlanner",
            "type": "boolean"
        },
        {
            "name": "sortOrder",
            "baseName": "sortOrder",
            "type": "number"
        },
        {
            "name": "filterableInPlanner",
            "baseName": "filterableInPlanner",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CustomFieldText.attributeTypeMap;
    }
}

export namespace CustomFieldText {
    export enum ModelEnum {
        Person = <any> 'PERSON',
        Project = <any> 'PROJECT'
    }
}
