/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Actor } from './actor';
import { EventContractDeletedContract } from './eventContractDeletedContract';

/**
* A contract was deleted.
*/
export class EventContractDeleted {
    'eventId': string;
    /**
    * The unique type of the event
    */
    'type': EventContractDeleted.TypeEnum;
    'actor': Actor;
    /**
    * The time the event occurred in ISO8601 format.
    */
    'timestamp': Date;
    'contract': EventContractDeletedContract;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "EventContractDeleted.TypeEnum"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "Actor"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "contract",
            "baseName": "contract",
            "type": "EventContractDeletedContract"
        }    ];

    static getAttributeTypeMap() {
        return EventContractDeleted.attributeTypeMap;
    }
}

export namespace EventContractDeleted {
    export enum TypeEnum {
        ContractDeleted = <any> 'contract_deleted'
    }
}
