/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventSubresourcePerson } from './eventSubresourcePerson';
import { EventSubresourceRole } from './eventSubresourceRole';

export class EventContractDeletedContract {
    /**
    * The unique identifier of the contract.
    */
    'id': number;
    /**
    * The unique identifier of the person associated with the contract.
    */
    'personId': number;
    /**
    * The unique identifier of the role associated with the contract.
    */
    'roleId': number;
    /**
    * The start date of the contract.
    */
    'startDate': string;
    /**
    * The end date of the contract. If the contract was ongoing, this field will be null.
    */
    'endDate': string;
    'person': EventSubresourcePerson;
    'role': EventSubresourceRole;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "EventSubresourcePerson"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "EventSubresourceRole"
        }    ];

    static getAttributeTypeMap() {
        return EventContractDeletedContract.attributeTypeMap;
    }
}

