/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Actor } from './actor';
import { EventActualDeleted } from './eventActualDeleted';
import { EventActualDeletedActual } from './eventActualDeletedActual';
import { EventAssignmentDeleted } from './eventAssignmentDeleted';
import { EventAssignmentDeletedAssignment } from './eventAssignmentDeletedAssignment';
import { EventContractDeleted } from './eventContractDeleted';
import { EventContractDeletedContract } from './eventContractDeletedContract';
import { EventPersonDeleted } from './eventPersonDeleted';
import { EventPersonDeletedPerson } from './eventPersonDeletedPerson';
import { EventProjectDeleted } from './eventProjectDeleted';
import { EventProjectDeletedProject } from './eventProjectDeletedProject';
import { EventTimeOffDeleted } from './eventTimeOffDeleted';
import { EventTimeOffDeletedTimeOff } from './eventTimeOffDeletedTimeOff';

/**
* An event represents an action that occurred.       Every event has a `type`, `actor`, and `timestamp` property.       Use the `type` property to determine which event occurred.
*/
export class Event {
    'eventId': string;
    /**
    * The unique type of the event
    */
    'type': Event.TypeEnum;
    'actor': Actor;
    /**
    * The time the event occurred in ISO8601 format.
    */
    'timestamp': Date;
    'project': EventProjectDeletedProject;
    'person': EventPersonDeletedPerson;
    'contract': EventContractDeletedContract;
    'actual': EventActualDeletedActual;
    'timeOff': EventTimeOffDeletedTimeOff;
    'assignment': EventAssignmentDeletedAssignment;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Event.TypeEnum"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "Actor"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "EventProjectDeletedProject"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "EventPersonDeletedPerson"
        },
        {
            "name": "contract",
            "baseName": "contract",
            "type": "EventContractDeletedContract"
        },
        {
            "name": "actual",
            "baseName": "actual",
            "type": "EventActualDeletedActual"
        },
        {
            "name": "timeOff",
            "baseName": "timeOff",
            "type": "EventTimeOffDeletedTimeOff"
        },
        {
            "name": "assignment",
            "baseName": "assignment",
            "type": "EventAssignmentDeletedAssignment"
        }    ];

    static getAttributeTypeMap() {
        return Event.attributeTypeMap;
    }
}

export namespace Event {
    export enum TypeEnum {
        ProjectDeleted = <any> 'project_deleted',
        PersonDeleted = <any> 'person_deleted',
        ContractDeleted = <any> 'contract_deleted',
        ActualDeleted = <any> 'actual_deleted',
        TimeOffDeleted = <any> 'time_off_deleted',
        AssignmentDeleted = <any> 'assignment_deleted'
    }
}
