/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventSubresourcePerson } from './eventSubresourcePerson';

export class EventTimeOffDeletedTimeOff {
    /**
    * The unique identifier for the time-off.
    */
    'id': number;
    /**
    * The identifier referencing the person associated with the time-off.
    */
    'personId': number;
    /**
    * The start date of the time-off.
    */
    'startDate': string;
    /**
    * The end date of the time-off.
    */
    'endDate': string;
    'note': string;
    'minutesPerDay': number;
    'person': EventSubresourcePerson;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "EventSubresourcePerson"
        }    ];

    static getAttributeTypeMap() {
        return EventTimeOffDeletedTimeOff.attributeTypeMap;
    }
}

