/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventSubresourcePerson } from './eventSubresourcePerson';
import { EventSubresourceProject } from './eventSubresourceProject';
import { EventSubresourceRole } from './eventSubresourceRole';
import { EventSubresourceWorkstream } from './eventSubresourceWorkstream';

/**
* Details about the actual that was deleted.
*/
export class EventActualDeletedActual {
    /**
    * The id of the actual at the time it was deleted.
    */
    'id': number;
    /**
    * The date of the actual at the time it was deleted.
    */
    'date': string;
    /**
    * The id of the person associated with the actual.
    */
    'personId': number;
    /**
    * The id of the role associated with the actual.
    */
    'roleId': number;
    /**
    * The id of the project associated with the actual.
    */
    'projectId': number;
    /**
    * The id referencing the phase of the actual, if applicable.
    */
    'phaseId': number;
    /**
    * The id of the workstream associated with the actual.
    */
    'workstreamId': number;
    /**
    * The number of billable minutes for the actual
    */
    'billableMinutes': number;
    /**
    * The number of nonbillable minutes for the actual
    */
    'nonbillableMinutes': number;
    /**
    * A note or comment related to the billable minutes, if any.
    */
    'billableNote': string;
    /**
    * A note or comment related to the nonbillable minutes, if any.
    */
    'nonbillableNote': string;
    'person': EventSubresourcePerson;
    'role': EventSubresourceRole;
    'project': EventSubresourceProject;
    'workstream': EventSubresourceWorkstream;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        },
        {
            "name": "billableMinutes",
            "baseName": "billableMinutes",
            "type": "number"
        },
        {
            "name": "nonbillableMinutes",
            "baseName": "nonbillableMinutes",
            "type": "number"
        },
        {
            "name": "billableNote",
            "baseName": "billableNote",
            "type": "string"
        },
        {
            "name": "nonbillableNote",
            "baseName": "nonbillableNote",
            "type": "string"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "EventSubresourcePerson"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "EventSubresourceRole"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "EventSubresourceProject"
        },
        {
            "name": "workstream",
            "baseName": "workstream",
            "type": "EventSubresourceWorkstream"
        }    ];

    static getAttributeTypeMap() {
        return EventActualDeletedActual.attributeTypeMap;
    }
}

