/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A subset of details about the person used on an event
*/
export class EventSubresourcePerson {
    /**
    * The unique identifier of the person
    */
    'id': number;
    /**
    * The first name of the person
    */
    'firstName': string;
    /**
    * The last name of the person
    */
    'lastName': string;
    /**
    * The email address of the person
    */
    'email': string;
    /**
    * A flag indicating if the person is a placeholder
    */
    'isPlaceholder': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "isPlaceholder",
            "baseName": "isPlaceholder",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EventSubresourcePerson.attributeTypeMap;
    }
}

