/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Actor } from './actor';
import { EventActualDeletedActual } from './eventActualDeletedActual';

/**
* An actual was deleted.
*/
export class EventActualDeleted {
    'eventId': string;
    /**
    * The unique type of the event
    */
    'type': EventActualDeleted.TypeEnum;
    'actor': Actor;
    /**
    * The time the event occurred in ISO8601 format.
    */
    'timestamp': Date;
    'actual': EventActualDeletedActual;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "EventActualDeleted.TypeEnum"
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "Actor"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "actual",
            "baseName": "actual",
            "type": "EventActualDeletedActual"
        }    ];

    static getAttributeTypeMap() {
        return EventActualDeleted.attributeTypeMap;
    }
}

export namespace EventActualDeleted {
    export enum TypeEnum {
        ActualDeleted = <any> 'actual_deleted'
    }
}
