/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetPersonCurrentContract404Response {
    'error': GetPersonCurrentContract404Response.ErrorEnum;
    'message': string;
    'statusCode': GetPersonCurrentContract404Response.StatusCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "GetPersonCurrentContract404Response.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "GetPersonCurrentContract404Response.StatusCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return GetPersonCurrentContract404Response.attributeTypeMap;
    }
}

export namespace GetPersonCurrentContract404Response {
    export enum ErrorEnum {
        NotFound = <any> 'Not Found'
    }
    export enum StatusCodeEnum {
        NUMBER_404 = <any> 404
    }
}
