/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Invitation {
    /**
    * Unique identifier for the invitation.
    */
    'id': number;
    /**
    * Email for the invitation.
    */
    'email': string;
    /**
    * Permission level
    */
    'userType': Invitation.UserTypeEnum;
    /**
    * Financial permission level
    */
    'financialPermission': Invitation.FinancialPermissionEnum;
    /**
    * Edit projects permission level (deprecated: use manageProjectsPermission)
    */
    'editProjectsPermission': Invitation.EditProjectsPermissionEnum;
    /**
    * Edit others permission level
    */
    'editOthersPermission': Invitation.EditOthersPermissionEnum;
    /**
    * Manage projects permission level
    */
    'manageProjectsPermission': Invitation.ManageProjectsPermissionEnum;
    /**
    * Manage people permission level
    */
    'managePeoplePermission': Invitation.ManagePeoplePermissionEnum;
    /**
    * Manage account permission level
    */
    'manageAccountPermission': boolean;
    /**
    * Add all people to projects permission level
    */
    'addAllPeopleToProjectsPermission': boolean;
    /**
    * View planner permission level
    */
    'viewPlannerPermission': boolean;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Date and time when the invitation was last sent
    */
    'sentAt': Date;
    /**
    * Date and time when the invitation expires
    */
    'expiresAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "userType",
            "type": "Invitation.UserTypeEnum"
        },
        {
            "name": "financialPermission",
            "baseName": "financialPermission",
            "type": "Invitation.FinancialPermissionEnum"
        },
        {
            "name": "editProjectsPermission",
            "baseName": "editProjectsPermission",
            "type": "Invitation.EditProjectsPermissionEnum"
        },
        {
            "name": "editOthersPermission",
            "baseName": "editOthersPermission",
            "type": "Invitation.EditOthersPermissionEnum"
        },
        {
            "name": "manageProjectsPermission",
            "baseName": "manageProjectsPermission",
            "type": "Invitation.ManageProjectsPermissionEnum"
        },
        {
            "name": "managePeoplePermission",
            "baseName": "managePeoplePermission",
            "type": "Invitation.ManagePeoplePermissionEnum"
        },
        {
            "name": "manageAccountPermission",
            "baseName": "manageAccountPermission",
            "type": "boolean"
        },
        {
            "name": "addAllPeopleToProjectsPermission",
            "baseName": "addAllPeopleToProjectsPermission",
            "type": "boolean"
        },
        {
            "name": "viewPlannerPermission",
            "baseName": "viewPlannerPermission",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "sentAt",
            "baseName": "sentAt",
            "type": "Date"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Invitation.attributeTypeMap;
    }
}

export namespace Invitation {
    export enum UserTypeEnum {
        Admin = <any> 'admin',
        Editor = <any> 'editor',
        ViewerAll = <any> 'viewer_all',
        ViewerBasic = <any> 'viewer_basic',
        TimesheetOnly = <any> 'timesheet_only',
        Manager = <any> 'manager',
        Contributor = <any> 'contributor'
    }
    export enum FinancialPermissionEnum {
        All = <any> 'all',
        NoSalaries = <any> 'no_salaries',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditOthersPermissionEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
    export enum ManageProjectsPermissionEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum ManagePeoplePermissionEnum {
        All = <any> 'all',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
}
