/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomCheckboxFieldCollection } from './customCheckboxFieldCollection';
import { CustomDateFieldCollection } from './customDateFieldCollection';
import { CustomSelectFieldCollection } from './customSelectFieldCollection';
import { CustomTextFieldCollection } from './customTextFieldCollection';
import { PersonCustomFieldsSelectInnerValuesInner } from './personCustomFieldsSelectInnerValuesInner';

export class PersonCustomFieldCustomFieldsInner {
    'name': string;
    'type': PersonCustomFieldCustomFieldsInner.TypeEnum;
    'customTextId': number;
    'value': Array<PersonCustomFieldsSelectInnerValuesInner>;
    'customDateId': number;
    'customCheckboxId': number;
    'customSelectId': number;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PersonCustomFieldCustomFieldsInner.TypeEnum"
        },
        {
            "name": "customTextId",
            "baseName": "customTextId",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<PersonCustomFieldsSelectInnerValuesInner>"
        },
        {
            "name": "customDateId",
            "baseName": "customDateId",
            "type": "number"
        },
        {
            "name": "customCheckboxId",
            "baseName": "customCheckboxId",
            "type": "number"
        },
        {
            "name": "customSelectId",
            "baseName": "customSelectId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PersonCustomFieldCustomFieldsInner.attributeTypeMap;
    }
}

export namespace PersonCustomFieldCustomFieldsInner {
    export enum TypeEnum {
        Text = <any> 'text',
        Date = <any> 'date',
        Checkbox = <any> 'checkbox',
        Select = <any> 'select'
    }
}
