/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PersonRequest {
    'id': number;
    /**
    * The ID of the placeholder associated with this request
    */
    'personId': number;
    'projectId': number;
    'status': PersonRequest.StatusEnum;
    /**
    * The ID of the user who requested this person
    */
    'requesterId': number;
    /**
    * The ID of the user who last updated this request
    */
    'updaterId': number;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PersonRequest.StatusEnum"
        },
        {
            "name": "requesterId",
            "baseName": "requesterId",
            "type": "number"
        },
        {
            "name": "updaterId",
            "baseName": "updaterId",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return PersonRequest.attributeTypeMap;
    }
}

export namespace PersonRequest {
    export enum StatusEnum {
        NeedToHire = <any> 'NEED_TO_HIRE',
        Requested = <any> 'REQUESTED',
        Pending = <any> 'PENDING'
    }
}
