/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionPersonManagersInner } from './collectionPersonManagersInner';
import { PersonCustomFields } from './personCustomFields';
import { PersonNotesInner } from './personNotesInner';
import { PersonSkillsInner } from './personSkillsInner';
import { Reference } from './reference';
import { Tag } from './tag';

export class Person {
    'id': number;
    'firstName': string;
    'lastName': string;
    'email': string;
    'isArchived': boolean;
    'references': Array<Reference>;
    'notes': Array<PersonNotesInner>;
    'teamId': number;
    'tags': Array<Tag>;
    'skills': Array<PersonSkillsInner>;
    'holidaysGroupId': number;
    'customFields': PersonCustomFields;
    'managers': Array<CollectionPersonManagersInner>;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "isArchived",
            "baseName": "isArchived",
            "type": "boolean"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "Array<PersonNotesInner>"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<Tag>"
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<PersonSkillsInner>"
        },
        {
            "name": "holidaysGroupId",
            "baseName": "holidaysGroupId",
            "type": "number"
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "PersonCustomFields"
        },
        {
            "name": "managers",
            "baseName": "managers",
            "type": "Array<CollectionPersonManagersInner>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Person.attributeTypeMap;
    }
}

