/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PersonCustomFieldsCheckboxInner } from './personCustomFieldsCheckboxInner';
import { PersonCustomFieldsDateInner } from './personCustomFieldsDateInner';
import { PersonCustomFieldsSelectInner } from './personCustomFieldsSelectInner';
import { PersonCustomFieldsTextInner } from './personCustomFieldsTextInner';

export class PersonCustomFields {
    'select': Array<PersonCustomFieldsSelectInner>;
    'text': Array<PersonCustomFieldsTextInner>;
    'checkbox': Array<PersonCustomFieldsCheckboxInner>;
    'date': Array<PersonCustomFieldsDateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "select",
            "baseName": "select",
            "type": "Array<PersonCustomFieldsSelectInner>"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "Array<PersonCustomFieldsTextInner>"
        },
        {
            "name": "checkbox",
            "baseName": "checkbox",
            "type": "Array<PersonCustomFieldsCheckboxInner>"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Array<PersonCustomFieldsDateInner>"
        }    ];

    static getAttributeTypeMap() {
        return PersonCustomFields.attributeTypeMap;
    }
}

