/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PersonCustomFields } from './personCustomFields';
import { Reference } from './reference';
import { Tag } from './tag';

export class Project {
    'id': number;
    'name': string;
    'isTemplate': boolean;
    'isArchived': boolean;
    'isConfirmed': boolean;
    'pricingModel': Project.PricingModelEnum;
    'rateType': Project.RateTypeEnum;
    'teamId': number;
    'budget': number;
    'expensesBudget': number;
    'references': Array<Reference>;
    'clientId': number;
    'rateCardId': number;
    'customFields': PersonCustomFields;
    'managerIds': Array<number>;
    'tags': Array<Tag>;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isTemplate",
            "baseName": "isTemplate",
            "type": "boolean"
        },
        {
            "name": "isArchived",
            "baseName": "isArchived",
            "type": "boolean"
        },
        {
            "name": "isConfirmed",
            "baseName": "isConfirmed",
            "type": "boolean"
        },
        {
            "name": "pricingModel",
            "baseName": "pricingModel",
            "type": "Project.PricingModelEnum"
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "Project.RateTypeEnum"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number"
        },
        {
            "name": "budget",
            "baseName": "budget",
            "type": "number"
        },
        {
            "name": "expensesBudget",
            "baseName": "expensesBudget",
            "type": "number"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "number"
        },
        {
            "name": "rateCardId",
            "baseName": "rateCardId",
            "type": "number"
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "PersonCustomFields"
        },
        {
            "name": "managerIds",
            "baseName": "managerIds",
            "type": "Array<number>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<Tag>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Project.attributeTypeMap;
    }
}

export namespace Project {
    export enum PricingModelEnum {
        Fp = <any> 'fp',
        Tm = <any> 'tm',
        Nb = <any> 'nb'
    }
    export enum RateTypeEnum {
        Hours = <any> 'hours',
        Days = <any> 'days'
    }
}
