/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ProjectAggregateActuals } from './projectAggregateActuals';
import { ProjectAggregateAssignments } from './projectAggregateAssignments';

export class ProjectAggregate {
    /**
    * The project identifier
    */
    'id': number;
    /**
    * Sum of billable minutes (using actuals if available, falling back to assignments)
    */
    'billableMinutes': number;
    /**
    * Sum of non-billable minutes (using actuals if available, falling back to assignments)
    */
    'nonBillableMinutes': number;
    /**
    * Total of the sums of billable and non-billable minutes
    */
    'totalMinutes': number;
    'assignments': ProjectAggregateAssignments;
    'actuals': ProjectAggregateActuals;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "billableMinutes",
            "baseName": "billableMinutes",
            "type": "number"
        },
        {
            "name": "nonBillableMinutes",
            "baseName": "nonBillableMinutes",
            "type": "number"
        },
        {
            "name": "totalMinutes",
            "baseName": "totalMinutes",
            "type": "number"
        },
        {
            "name": "assignments",
            "baseName": "assignments",
            "type": "ProjectAggregateAssignments"
        },
        {
            "name": "actuals",
            "baseName": "actuals",
            "type": "ProjectAggregateActuals"
        }    ];

    static getAttributeTypeMap() {
        return ProjectAggregate.attributeTypeMap;
    }
}

