/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Project phases divide your project into smaller sections so you can group similar tasks and assignments together.
*/
export class ProjectPhase {
    /**
    * Unique identifier for the phase
    */
    'id': number;
    /**
    * The name of the project phase
    */
    'name': string;
    /**
    * Color of the project phase (hex code)
    */
    'color': string;
    /**
    * Start date of the project phase in ISO 8601 format
    */
    'startDate': string;
    /**
    * End date of the phase in ISO 8601 format
    */
    'endDate': string;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * The project the phase is associated with.
    */
    'projectId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProjectPhase.attributeTypeMap;
    }
}

