/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A non-labour expense for a project.
*/
export class ProjectOtherExpense1 {
    /**
    * How much the item costs for your business (in your account\'s currency).
    */
    'cost'?: number;
    /**
    * How much you are charging your clients for the item (in your account\'s currency).
    */
    'charge'?: number;
    /**
    * The item or service that was purchased.
    */
    'name'?: string;
    /**
    * The date the expense was incurred.
    */
    'date'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number"
        },
        {
            "name": "charge",
            "baseName": "charge",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProjectOtherExpense1.attributeTypeMap;
    }
}

