/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateRateCardRequestReferencesInner } from './createRateCardRequestReferencesInner';
import { RateCardRatesInner } from './rateCardRatesInner';

export class RateCard {
    'id': number;
    'name': string;
    'description': string;
    'isArchived': boolean;
    'references': Array<CreateRateCardRequestReferencesInner>;
    'isBlendedRateCard': boolean;
    'blendedRate': number;
    'rateType': RateCard.RateTypeEnum;
    'projectIds': Array<number>;
    'rates': Array<RateCardRatesInner>;
    /**
    * Timestamp of when the object was created.
    */
    'createdAt': Date;
    /**
    * Timestamp of when the object was last updated.
    */
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isArchived",
            "baseName": "isArchived",
            "type": "boolean"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<CreateRateCardRequestReferencesInner>"
        },
        {
            "name": "isBlendedRateCard",
            "baseName": "isBlendedRateCard",
            "type": "boolean"
        },
        {
            "name": "blendedRate",
            "baseName": "blendedRate",
            "type": "number"
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "RateCard.RateTypeEnum"
        },
        {
            "name": "projectIds",
            "baseName": "projectIds",
            "type": "Array<number>"
        },
        {
            "name": "rates",
            "baseName": "rates",
            "type": "Array<RateCardRatesInner>"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return RateCard.attributeTypeMap;
    }
}

export namespace RateCard {
    export enum RateTypeEnum {
        Hours = <any> 'hours',
        Days = <any> 'days'
    }
}
