/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReportsHoursPeopleActuals } from './reportsHoursPeopleActuals';
import { ReportsHoursPeopleAssignments } from './reportsHoursPeopleAssignments';

export class ReportsHoursProjects {
    /**
    * The date of the entry. Multi-day assignments will get split over multiple days. Format: YYYY-MM-DD
    */
    'date': string;
    /**
    * The project-specific role for the associated person
    */
    'roleId': number;
    /**
    * The person related to this entry
    */
    'personId': number;
    /**
    * The project for this entry
    */
    'projectId': number;
    /**
    * The workstream for this entry
    */
    'workstreamId': number;
    /**
    * Associated phase (using actual phase, and falling back to assignment phase)
    */
    'phaseId': number;
    /**
    * Billable minutes for this day. Returns Actual minutes where it exists, otherwise returns Assignment minutes.
    */
    'billableMinutes': number;
    /**
    * Non-billable minutes for this day. Returns Actual minutes where it exists, otherwise returns Assignment minutes.
    */
    'nonBillableMinutes': number;
    /**
    * Total minutes for this day (sum of billable and non-billable)
    */
    'totalMinutes': number;
    'assignments': ReportsHoursPeopleAssignments;
    'actuals': ReportsHoursPeopleActuals;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "number"
        },
        {
            "name": "workstreamId",
            "baseName": "workstreamId",
            "type": "number"
        },
        {
            "name": "phaseId",
            "baseName": "phaseId",
            "type": "number"
        },
        {
            "name": "billableMinutes",
            "baseName": "billableMinutes",
            "type": "number"
        },
        {
            "name": "nonBillableMinutes",
            "baseName": "nonBillableMinutes",
            "type": "number"
        },
        {
            "name": "totalMinutes",
            "baseName": "totalMinutes",
            "type": "number"
        },
        {
            "name": "assignments",
            "baseName": "assignments",
            "type": "ReportsHoursPeopleAssignments"
        },
        {
            "name": "actuals",
            "baseName": "actuals",
            "type": "ReportsHoursPeopleActuals"
        }    ];

    static getAttributeTypeMap() {
        return ReportsHoursProjects.attributeTypeMap;
    }
}

