/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TimeOffLeaveInput {
    /**
    * The unique identifier for the person.
    */
    'personId': number;
    /**
    * The start date of the time-off. Format: YYYY-MM-DD
    */
    'startDate': string;
    /**
    * The end date of the time-off. Format: YYYY-MM-DD
    */
    'endDate': string;
    /**
    * A note or comment related to the time-off, if any.
    */
    'note'?: string;
    /**
    * The minutes per day taken as time off. Omit this property if time-off is for full day(s) as per person\'s contract.
    */
    'minutesPerDay'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TimeOffLeaveInput.attributeTypeMap;
    }
}

