/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TimeOffHolidayInput {
    /**
    * The unique identifier for the person.
    */
    'personId': number;
    /**
    * A note or comment related to the time-off, if any.
    */
    'note'?: string;
    /**
    * The unique identifier for the holiday.
    */
    'holidayId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "personId",
            "baseName": "personId",
            "type": "number"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "holidayId",
            "baseName": "holidayId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TimeOffHolidayInput.attributeTypeMap;
    }
}

