/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Unauthorized {
    'error': Unauthorized.ErrorEnum;
    'message': Unauthorized.MessageEnum;
    'statusCode': Unauthorized.StatusCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "Unauthorized.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "Unauthorized.MessageEnum"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "Unauthorized.StatusCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Unauthorized.attributeTypeMap;
    }
}

export namespace Unauthorized {
    export enum ErrorEnum {
        Unauthorized = <any> 'Unauthorized'
    }
    export enum MessageEnum {
        Unauthorized = <any> 'Unauthorized'
    }
    export enum StatusCodeEnum {
        NUMBER_401 = <any> 401
    }
}
