/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateProjectBudgetRoleRequestAnyOf } from './updateProjectBudgetRoleRequestAnyOf';
import { UpdateProjectBudgetRoleRequestAnyOf1 } from './updateProjectBudgetRoleRequestAnyOf1';

export class UpdateProjectBudgetRoleRequest {
    'estimatedMinutes': number;
    'estimatedBudget': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "estimatedMinutes",
            "baseName": "estimatedMinutes",
            "type": "number"
        },
        {
            "name": "estimatedBudget",
            "baseName": "estimatedBudget",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateProjectBudgetRoleRequest.attributeTypeMap;
    }
}

