/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateProjectPhaseRequest {
    /**
    * The name of the project phase. Must be at least 1 character long.
    */
    'name'?: string;
    /**
    * The start date of the project phase in ISO8061 format: YYYY-MM-DD
    */
    'startDate'?: string;
    /**
    * The end date of the project phase in ISO8061 format: YYYY-MM-DD
    */
    'endDate'?: string;
    /**
    * Hex color of the phase. Only a subset of colors is allowed.
    */
    'color'?: UpdateProjectPhaseRequest.ColorEnum = UpdateProjectPhaseRequest.ColorEnum._67D0D5;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "UpdateProjectPhaseRequest.ColorEnum"
        }    ];

    static getAttributeTypeMap() {
        return UpdateProjectPhaseRequest.attributeTypeMap;
    }
}

export namespace UpdateProjectPhaseRequest {
    export enum ColorEnum {
        _67D0D5 = <any> '#67D0D5',
        Fdcd4F = <any> '#FDCD4F',
        F191Cc = <any> '#F191CC',
        B19De6 = <any> '#B19DE6',
        _9Ce277 = <any> '#9CE277',
        Cd97Da = <any> '#CD97DA',
        _84Dba0 = <any> '#84DBA0',
        Ffb077 = <any> '#FFB077',
        _9Cc5Bf = <any> '#9CC5BF',
        E8C681 = <any> '#E8C681',
        _6899F1 = <any> '#6899F1',
        Ddae9F = <any> '#DDAE9F'
    }
}
