/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateContractRequestRosteredDays } from './updateContractRequestRosteredDays';

export class UpdateContractRequest {
    'roleId'?: number;
    'startDate'?: string;
    'endDate'?: string;
    'employmentType'?: UpdateContractRequest.EmploymentTypeEnum;
    'costPerHour'?: number;
    'minutesPerDay'?: number;
    'rosteredDays'?: UpdateContractRequestRosteredDays;
    'jobTitle'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "number"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "employmentType",
            "baseName": "employmentType",
            "type": "UpdateContractRequest.EmploymentTypeEnum"
        },
        {
            "name": "costPerHour",
            "baseName": "costPerHour",
            "type": "number"
        },
        {
            "name": "minutesPerDay",
            "baseName": "minutesPerDay",
            "type": "number"
        },
        {
            "name": "rosteredDays",
            "baseName": "rosteredDays",
            "type": "UpdateContractRequestRosteredDays"
        },
        {
            "name": "jobTitle",
            "baseName": "jobTitle",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateContractRequest.attributeTypeMap;
    }
}

export namespace UpdateContractRequest {
    export enum EmploymentTypeEnum {
        Employee = <any> 'employee',
        Contractor = <any> 'contractor'
    }
}
