/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Reference } from './reference';
import { UpdatePersonRequestTagsInner } from './updatePersonRequestTagsInner';

export class UpdateProjectRequest {
    'name'?: string;
    'isConfirmed'?: boolean;
    'isArchived'?: boolean;
    'isTemplate'?: boolean;
    /**
    * Budget value in local currency
    */
    'budget'?: number;
    /**
    * Expenses budget value in local currency
    */
    'expensesBudget'?: number;
    'clientId'?: number;
    'teamId'?: number;
    'pricingModel'?: UpdateProjectRequest.PricingModelEnum;
    'rateType'?: UpdateProjectRequest.RateTypeEnum;
    'references'?: Array<Reference>;
    'tags'?: Array<UpdatePersonRequestTagsInner>;
    /**
    * List of User IDs that manage the project.
    */
    'managerIds'?: Set<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "isConfirmed",
            "baseName": "isConfirmed",
            "type": "boolean"
        },
        {
            "name": "isArchived",
            "baseName": "isArchived",
            "type": "boolean"
        },
        {
            "name": "isTemplate",
            "baseName": "isTemplate",
            "type": "boolean"
        },
        {
            "name": "budget",
            "baseName": "budget",
            "type": "number"
        },
        {
            "name": "expensesBudget",
            "baseName": "expensesBudget",
            "type": "number"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "number"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "number"
        },
        {
            "name": "pricingModel",
            "baseName": "pricingModel",
            "type": "UpdateProjectRequest.PricingModelEnum"
        },
        {
            "name": "rateType",
            "baseName": "rateType",
            "type": "UpdateProjectRequest.RateTypeEnum"
        },
        {
            "name": "references",
            "baseName": "references",
            "type": "Array<Reference>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<UpdatePersonRequestTagsInner>"
        },
        {
            "name": "managerIds",
            "baseName": "managerIds",
            "type": "Set<number>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateProjectRequest.attributeTypeMap;
    }
}

export namespace UpdateProjectRequest {
    export enum PricingModelEnum {
        Fp = <any> 'fp',
        Tm = <any> 'tm',
        Nb = <any> 'nb'
    }
    export enum RateTypeEnum {
        Hours = <any> 'hours',
        Days = <any> 'days'
    }
}
