/**
 * Runn API
 * <p>See <a target=\"_blank\" href=\"https://help.runn.io/en/articles/8579592-api-v1-beta\" title=\"Runn API full documentation\">the full documentation and guide</a> to using the Runn API.</p><p>The domain for your API endpoint can be found in <strong>Accounts > Settings > API</strong> in your Runn application</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserPermissions {
    'type': UserPermissions.TypeEnum;
    'financial': UserPermissions.FinancialEnum;
    'editProjects': UserPermissions.EditProjectsEnum;
    'manageProjects': UserPermissions.ManageProjectsEnum;
    'editOthers': UserPermissions.EditOthersEnum;
    'managePeople': UserPermissions.ManagePeopleEnum;
    'manageAccount': boolean;
    'addAllPeopleToProjects': boolean;
    'viewPlanner': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UserPermissions.TypeEnum"
        },
        {
            "name": "financial",
            "baseName": "financial",
            "type": "UserPermissions.FinancialEnum"
        },
        {
            "name": "editProjects",
            "baseName": "editProjects",
            "type": "UserPermissions.EditProjectsEnum"
        },
        {
            "name": "manageProjects",
            "baseName": "manageProjects",
            "type": "UserPermissions.ManageProjectsEnum"
        },
        {
            "name": "editOthers",
            "baseName": "editOthers",
            "type": "UserPermissions.EditOthersEnum"
        },
        {
            "name": "managePeople",
            "baseName": "managePeople",
            "type": "UserPermissions.ManagePeopleEnum"
        },
        {
            "name": "manageAccount",
            "baseName": "manageAccount",
            "type": "boolean"
        },
        {
            "name": "addAllPeopleToProjects",
            "baseName": "addAllPeopleToProjects",
            "type": "boolean"
        },
        {
            "name": "viewPlanner",
            "baseName": "viewPlanner",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UserPermissions.attributeTypeMap;
    }
}

export namespace UserPermissions {
    export enum TypeEnum {
        Superuser = <any> 'superuser',
        Admin = <any> 'admin',
        Editor = <any> 'editor',
        ViewerAll = <any> 'viewer_all',
        ViewerBasic = <any> 'viewer_basic',
        TimesheetOnly = <any> 'timesheet_only'
    }
    export enum FinancialEnum {
        All = <any> 'all',
        NoSalaries = <any> 'no_salaries',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditProjectsEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum ManageProjectsEnum {
        All = <any> 'all',
        Specific = <any> 'specific',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
    export enum EditOthersEnum {
        All = <any> 'all',
        None = <any> 'none'
    }
    export enum ManagePeopleEnum {
        All = <any> 'all',
        Restricted = <any> 'restricted',
        None = <any> 'none'
    }
}
